[package]
name = "rawshift-image-arw"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Sony ARW decoding for rawshift"

[dependencies]
rawshift-image-core = { workspace = true }
rawshift-image-ifd = { workspace = true, optional = true }
rawshift-image-ljpeg = { workspace = true, optional = true }
gamut-ifd = { workspace = true, optional = true, features = ["bigtiff"] }
tracing = { workspace = true, optional = true }

[features]
default = ["decode"]
decode = ["dep:rawshift-image-ifd", "dep:rawshift-image-ljpeg", "dep:gamut-ifd", "dep:tracing"]
