//! Safe wrapper around libaom's C AV1 encoder, muxed into AVIF via `avif-serialize`.
//!
//! All `unsafe`/FFI interaction with libaom is confined to this module (the
//! `src/codecs` safety boundary — see `PRINCIPLES.md`). Callers receive a plain
//! `Vec<u8>` (a complete `.avif` file) and `Result<_, String>`;
//! `src/formats/encode.rs` maps the `String` into
//! [`EncodeError::Encoding`](crate::error::EncodeError::Encoding).
//!
//! libaom only produces a raw AV1 bitstream (OBUs); the BSD-3 `avif-serialize`
//! crate wraps it in the AVIF (ISO-BMFF) container. Pixels are encoded as
//! **full-range BT.709 YUV 4:4:4** (no chroma subsampling — what `avif-serialize`
//! expects by default, and what AV1 handles best) at 8/10/12 bits. The signalled
//! CICP matches both the RGB→YUV conversion here and the container's `colr` box.
//!
//! The raw bindings are generated by `build.rs` (bindgen over libaom's BSD-2
//! headers) into `$OUT_DIR/aom_bindings.rs` and `include!`d below — we vendor no
//! GPL bindings.

use std::ffi::CStr;
use std::os::raw::{c_int, c_uint};
use std::ptr;

/// Generated libaom C-API bindings (see `build.rs`). bindgen output, so the usual
/// non-idiomatic-naming and clippy lints are silenced wholesale.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    improper_ctypes,
    clippy::all,
    clippy::pedantic
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/aom_bindings.rs"));
}

/// Fully-resolved libaom encoder settings.
///
/// This is the plain-data contract between [`crate::formats::encode`] and the FFI
/// layer: every field is already the integer libaom expects.
#[derive(Debug, Clone)]
pub struct AvifLibaomParams {
    /// Constant-quantiser level, `0..=63` (`AOME_SET_CQ_LEVEL`). Lower is better
    /// quality and larger files.
    pub cq_level: u32,
    /// `rc_min_quantizer`, `0..=63`.
    pub min_quantizer: u32,
    /// `rc_max_quantizer`, `0..=63`.
    pub max_quantizer: u32,
    /// Speed/quality trade-off, `0` (slowest, best) ..= `8` (fastest)
    /// (`AOME_SET_CPUUSED`).
    pub cpu_used: u32,
    /// `true` selects constant-quality (`AOM_Q`); `false` selects
    /// constrained-quality (`AOM_CQ`).
    pub constant_quality: bool,
}

/// Owns an `aom_codec_ctx_t`; destroys it on drop, but only once successfully
/// initialised (libaom must not be destroyed if `enc_init` failed).
struct Codec {
    ctx: ffi::aom_codec_ctx_t,
    initialized: bool,
}
impl Drop for Codec {
    fn drop(&mut self) {
        if self.initialized {
            unsafe { ffi::aom_codec_destroy(&mut self.ctx) };
        }
    }
}

/// Owns an `aom_image_t`; frees its plane buffers on drop, but only once
/// `aom_img_alloc` has succeeded.
struct Image {
    img: ffi::aom_image_t,
    allocated: bool,
}
impl Drop for Image {
    fn drop(&mut self) {
        if self.allocated {
            unsafe { ffi::aom_img_free(&mut self.img) };
        }
    }
}

/// Encode interleaved 16-bit RGB to a complete AVIF file.
///
/// `rgb16` is `width * height * 3` samples, each normalised to `[0, 65535]` (the
/// crate's display-referred sRGB convention). `depth` is the output bit depth: 8,
/// 10, or 12. EXIF/ICC/XMP are appended by the caller.
pub fn encode(
    rgb16: &[u16],
    width: u32,
    height: u32,
    depth: u8,
    params: &AvifLibaomParams,
) -> Result<Vec<u8>, String> {
    if !matches!(depth, 8 | 10 | 12) {
        return Err(format!("unsupported AV1 bit depth: {depth}"));
    }
    if width == 0 || height == 0 {
        return Err("image dimensions must be non-zero".into());
    }
    let npx = (width as usize) * (height as usize);
    let expected = npx * 3;
    if rgb16.len() != expected {
        return Err(format!(
            "pixel buffer length mismatch: expected {expected}, got {}",
            rgb16.len()
        ));
    }

    // RGB → full-range BT.709 YUV 4:4:4 at the target depth.
    let (y_plane, u_plane, v_plane) = rgb_to_yuv444_bt709(rgb16, npx, depth);

    let obu = encode_av1(&y_plane, &u_plane, &v_plane, width, height, depth, params)?;

    // Mux the AV1 bitstream into an AVIF container. The CICP set here must match
    // the conversion above (and the AV1E_SET_* controls in `encode_av1`).
    use avif_serialize::constants::{ColorPrimaries, MatrixCoefficients, TransferCharacteristics};
    let mut out = Vec::new();
    avif_serialize::Aviffy::new()
        .set_color_primaries(ColorPrimaries::Bt709)
        .set_transfer_characteristics(TransferCharacteristics::Srgb)
        .set_matrix_coefficients(MatrixCoefficients::Bt709)
        .set_full_color_range(true)
        .write(&mut out, &obu, None, width, height, depth)
        .map_err(|e| format!("AVIF muxing failed: {e}"))?;
    Ok(out)
}

/// Full-range BT.709 RGB→YUV 4:4:4. Returns the Y, U, V planes (one sample per
/// pixel each), with values in `[0, 2^depth - 1]` stored in `u16`.
fn rgb_to_yuv444_bt709(rgb16: &[u16], npx: usize, depth: u8) -> (Vec<u16>, Vec<u16>, Vec<u16>) {
    let shift = 16 - u32::from(depth);
    let max = ((1u32 << depth) - 1) as f32;
    let half = (1u32 << (depth - 1)) as f32;

    let mut yb = vec![0u16; npx];
    let mut ub = vec![0u16; npx];
    let mut vb = vec![0u16; npx];

    let q = |x: f32| x.round().clamp(0.0, max) as u16;
    for i in 0..npx {
        let r = f32::from(rgb16[i * 3] >> shift);
        let g = f32::from(rgb16[i * 3 + 1] >> shift);
        let b = f32::from(rgb16[i * 3 + 2] >> shift);
        let y = 0.2126 * r + 0.7152 * g + 0.0722 * b;
        yb[i] = q(y);
        ub[i] = q((b - y) / 1.8556 + half);
        vb[i] = q((r - y) / 1.5748 + half);
    }
    (yb, ub, vb)
}

/// Encode the YUV 4:4:4 planes to a single AV1 keyframe and return its bitstream.
fn encode_av1(
    y: &[u16],
    u: &[u16],
    v: &[u16],
    width: u32,
    height: u32,
    depth: u8,
    params: &AvifLibaomParams,
) -> Result<Vec<u8>, String> {
    unsafe {
        let iface = ffi::aom_codec_av1_cx();
        if iface.is_null() {
            return Err("aom_codec_av1_cx returned null".into());
        }

        // Default config tuned for a single still image (all-intra), then override
        // the fields we care about.
        let mut cfg: ffi::aom_codec_enc_cfg_t = std::mem::zeroed();
        let e = ffi::aom_codec_enc_config_default(iface, &mut cfg, ffi::AOM_USAGE_ALL_INTRA);
        if e != ffi::AOM_CODEC_OK {
            return Err(format!(
                "aom_codec_enc_config_default failed: {}",
                err_str(e)
            ));
        }
        cfg.g_w = width;
        cfg.g_h = height;
        // 4:4:4 requires AV1 seq profile 1 (8/10-bit) or 2 (12-bit).
        cfg.g_profile = if depth >= 12 { 2 } else { 1 };
        cfg.g_bit_depth = match depth {
            8 => ffi::AOM_BITS_8,
            10 => ffi::AOM_BITS_10,
            _ => ffi::AOM_BITS_12,
        };
        cfg.g_input_bit_depth = u32::from(depth);
        cfg.g_pass = ffi::AOM_RC_ONE_PASS;
        cfg.g_lag_in_frames = 0;
        cfg.monochrome = 0;
        cfg.rc_end_usage = if params.constant_quality {
            ffi::AOM_Q
        } else {
            ffi::AOM_CQ
        };
        cfg.rc_min_quantizer = params.min_quantizer;
        cfg.rc_max_quantizer = params.max_quantizer;
        if let Ok(n) = std::thread::available_parallelism() {
            cfg.g_threads = n.get().min(16) as c_uint;
        }

        let flags: ffi::aom_codec_flags_t = if depth > 8 {
            ffi::AOM_CODEC_USE_HIGHBITDEPTH as ffi::aom_codec_flags_t
        } else {
            0
        };
        let mut codec = Codec {
            ctx: std::mem::zeroed(),
            initialized: false,
        };
        let e = ffi::aom_codec_enc_init_ver(
            &mut codec.ctx,
            iface,
            &cfg,
            flags,
            ffi::AOM_ENCODER_ABI_VERSION as c_int,
        );
        if e != ffi::AOM_CODEC_OK {
            return Err(format!("aom_codec_enc_init_ver failed: {}", err_str(e)));
        }
        codec.initialized = true;

        // Speed, quality, and CICP (must match the muxer's `colr` box).
        control(
            &mut codec.ctx,
            ffi::AOME_SET_CPUUSED,
            params.cpu_used as c_int,
        )?;
        control(
            &mut codec.ctx,
            ffi::AOME_SET_CQ_LEVEL,
            params.cq_level as c_int,
        )?;
        control(
            &mut codec.ctx,
            ffi::AV1E_SET_COLOR_PRIMARIES,
            ffi::AOM_CICP_CP_BT_709 as c_int,
        )?;
        control(
            &mut codec.ctx,
            ffi::AV1E_SET_TRANSFER_CHARACTERISTICS,
            ffi::AOM_CICP_TC_SRGB as c_int,
        )?;
        control(
            &mut codec.ctx,
            ffi::AV1E_SET_MATRIX_COEFFICIENTS,
            ffi::AOM_CICP_MC_BT_709 as c_int,
        )?;
        control(
            &mut codec.ctx,
            ffi::AV1E_SET_COLOR_RANGE,
            ffi::AOM_CR_FULL_RANGE as c_int,
        )?;

        // Allocate the input image (4:4:4, high-bit-depth container for 10/12) and
        // copy the planes in.
        let fmt = if depth > 8 {
            ffi::AOM_IMG_FMT_I44416
        } else {
            ffi::AOM_IMG_FMT_I444
        };
        let mut image = Image {
            img: std::mem::zeroed(),
            allocated: false,
        };
        if ffi::aom_img_alloc(&mut image.img, fmt, width, height, 1).is_null() {
            return Err("aom_img_alloc failed".into());
        }
        image.allocated = true;
        image.img.bit_depth = u32::from(depth);
        fill_plane(
            &mut image.img,
            ffi::AOM_PLANE_Y as usize,
            y,
            width,
            height,
            depth,
        );
        fill_plane(
            &mut image.img,
            ffi::AOM_PLANE_U as usize,
            u,
            width,
            height,
            depth,
        );
        fill_plane(
            &mut image.img,
            ffi::AOM_PLANE_V as usize,
            v,
            width,
            height,
            depth,
        );

        // Encode the single frame, then flush (img = null) so all packets are emitted.
        let e = ffi::aom_codec_encode(
            &mut codec.ctx,
            &image.img,
            0,
            1,
            ffi::AOM_EFLAG_FORCE_KF as ffi::aom_enc_frame_flags_t,
        );
        if e != ffi::AOM_CODEC_OK {
            return Err(format!("aom_codec_encode failed: {}", err_str(e)));
        }
        let e = ffi::aom_codec_encode(&mut codec.ctx, ptr::null(), 0, 1, 0);
        if e != ffi::AOM_CODEC_OK {
            return Err(format!("aom_codec_encode(flush) failed: {}", err_str(e)));
        }

        // Drain compressed-frame packets into a single OBU buffer.
        let mut out = Vec::new();
        let mut iter: ffi::aom_codec_iter_t = ptr::null();
        loop {
            let pkt = ffi::aom_codec_get_cx_data(&mut codec.ctx, &mut iter);
            if pkt.is_null() {
                break;
            }
            if (*pkt).kind == ffi::AOM_CODEC_CX_FRAME_PKT {
                let frame = &(*pkt).data.frame;
                let bytes = std::slice::from_raw_parts(frame.buf.cast::<u8>(), frame.sz);
                out.extend_from_slice(bytes);
            }
        }
        if out.is_empty() {
            return Err("libaom produced no output".into());
        }
        Ok(out)
    }
}

/// Issue one `aom_codec_control` and convert a non-OK status to an error string.
unsafe fn control(ctx: *mut ffi::aom_codec_ctx_t, id: c_int, val: c_int) -> Result<(), String> {
    let e = unsafe { ffi::aom_codec_control(ctx, id, val) };
    if e != ffi::AOM_CODEC_OK {
        return Err(format!("aom_codec_control(id={id}) failed: {}", unsafe {
            err_str(e)
        }));
    }
    Ok(())
}

/// Copy a planar YUV channel into a libaom-allocated plane, honouring its byte
/// stride and (for 10/12-bit) the 16-bit sample container.
unsafe fn fill_plane(
    img: &mut ffi::aom_image_t,
    plane: usize,
    src: &[u16],
    width: u32,
    height: u32,
    depth: u8,
) {
    let stride = img.stride[plane] as usize; // bytes between rows
    let base = img.planes[plane];
    let w = width as usize;
    for row in 0..height as usize {
        let dst = unsafe { base.add(row * stride) };
        let srow = &src[row * w..row * w + w];
        if depth == 8 {
            for (x, &s) in srow.iter().enumerate() {
                unsafe { *dst.add(x) = s as u8 };
            }
        } else {
            let dst16 = dst.cast::<u16>();
            for (x, &s) in srow.iter().enumerate() {
                unsafe { *dst16.add(x) = s };
            }
        }
    }
}

/// Human-readable string for a libaom error code.
unsafe fn err_str(err: ffi::aom_codec_err_t) -> String {
    let p = unsafe { ffi::aom_codec_err_to_string(err) };
    if p.is_null() {
        return format!("error {err}");
    }
    unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `w`×`h` RGB16 gradient.
    fn gradient(w: u32, h: u32) -> Vec<u16> {
        let mut px = Vec::with_capacity((w * h * 3) as usize);
        for y in 0..h {
            for x in 0..w {
                px.push((u32::from(x) * 65535 / u32::from(w.max(2) - 1)) as u16);
                px.push((u32::from(y) * 65535 / u32::from(h.max(2) - 1)) as u16);
                px.push(32768);
            }
        }
        px
    }

    fn params() -> AvifLibaomParams {
        AvifLibaomParams {
            cq_level: 30,
            min_quantizer: 0,
            max_quantizer: 63,
            cpu_used: 6,
            constant_quality: true,
        }
    }

    /// The bytes are a valid ISO-BMFF AVIF file (`ftyp` box, `avif`/`avis` brand).
    fn is_avif(data: &[u8]) -> bool {
        data.len() > 12 && &data[4..8] == b"ftyp" && {
            let brand = &data[8..12];
            brand == b"avif" || brand == b"avis" || brand == b"mif1"
        }
    }

    #[test]
    #[cfg_attr(miri, ignore)] // FFI into libaom cannot run under Miri.
    fn encodes_8bit_avif() {
        let data = encode(&gradient(16, 12), 16, 12, 8, &params()).expect("encode 8-bit");
        assert!(is_avif(&data), "expected a valid AVIF container");
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn encodes_10bit_avif() {
        let data = encode(&gradient(16, 12), 16, 12, 10, &params()).expect("encode 10-bit");
        assert!(is_avif(&data));
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn encodes_12bit_avif() {
        let data = encode(&gradient(16, 12), 16, 12, 12, &params()).expect("encode 12-bit");
        assert!(is_avif(&data));
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn rejects_wrong_buffer_length() {
        assert!(encode(&[0u16; 10], 16, 12, 8, &params()).is_err());
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn rejects_bad_depth() {
        assert!(encode(&gradient(4, 4), 4, 4, 16, &params()).is_err());
    }
}
