//! Safe wrapper around jpegli's encode API, via the C++ setjmp shim.
//!
//! All `unsafe`/FFI interaction with jpegli is confined to this module and
//! `jpegli_shim.cc` (the `src/codecs` safety boundary — see `PRINCIPLES.md`).
//! Callers receive a plain `Vec<u8>` JPEG and `Result<_, String>`;
//! `src/formats/encode.rs` maps the `String` into
//! [`EncodeError::Jpegli`](crate::error::EncodeError::Jpegli).
//!
//! The shim's C ABI is generated by `build.rs` (bindgen over `jpegli_shim.h`)
//! into `$OUT_DIR/jpegli_bindings.rs` and `include!`d below — jpegli's own
//! libjpeg-style error model (`error_exit`/`setjmp`) is handled entirely in the
//! shim, so this layer is a thin marshal-in / copy-out.

use std::os::raw::{c_char, c_int};
use std::ptr;

/// Generated jpegli shim bindings (see `build.rs`). bindgen output, so the usual
/// non-idiomatic-naming and clippy lints are silenced wholesale.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    improper_ctypes,
    clippy::all,
    clippy::pedantic
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/jpegli_bindings.rs"));
}

/// Chroma subsampling preset. Applied only in non-XYB mode (XYB picks its own).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Subsampling {
    /// 4:2:0
    Yuv420,
    /// 4:2:2
    Yuv422,
    /// 4:4:4
    Yuv444,
}

/// Fully-resolved jpegli encoder settings — the plain-data contract between
/// [`crate::formats::encode`] and the FFI layer.
#[derive(Debug, Clone)]
pub struct JpegliEncodeParams {
    /// JPEG-style quality `1..=100`; when `Some`, used instead of `distance`.
    pub quality: Option<u8>,
    /// Butteraugli distance (`0.0` ≈ visually lossless), used when `quality` is `None`.
    pub distance: f32,
    /// Emit a progressive JPEG.
    pub progressive: bool,
    /// Encode in jpegli's XYB high-fidelity mode.
    pub xyb: bool,
    /// Chroma subsampling.
    pub subsampling: Subsampling,
}

impl Default for JpegliEncodeParams {
    fn default() -> Self {
        Self {
            quality: None,
            distance: 1.0,
            progressive: true,
            xyb: false,
            subsampling: Subsampling::Yuv420,
        }
    }
}

/// Encode interleaved RGB samples to a JPEG via jpegli.
///
/// `samples` is packed RGB with no alpha: `width * height * 3` bytes for
/// `bits_per_sample == 8`, or `width * height * 3 * 2` native-endian bytes for
/// `bits_per_sample == 16` (jpegli quantizes from the higher precision, reducing
/// banding). The image is encoded as sRGB; EXIF/ICC/XMP are appended by the caller.
pub fn encode(
    samples: &[u8],
    width: u32,
    height: u32,
    bits_per_sample: u32,
    params: &JpegliEncodeParams,
) -> Result<Vec<u8>, String> {
    let subsampling = match params.subsampling {
        Subsampling::Yuv420 => ffi::RAWSHIFT_JPEGLI_SUBSAMPLE_420,
        Subsampling::Yuv422 => ffi::RAWSHIFT_JPEGLI_SUBSAMPLE_422,
        Subsampling::Yuv444 => ffi::RAWSHIFT_JPEGLI_SUBSAMPLE_444,
    };
    let input = ffi::RawshiftJpegliInput {
        pixels: samples.as_ptr(),
        pixels_len: samples.len(),
        width,
        height,
        bits_per_sample,
        use_distance: c_int::from(params.quality.is_none()),
        distance: params.distance,
        quality: c_int::from(params.quality.unwrap_or(0)),
        progressive: c_int::from(params.progressive),
        xyb: c_int::from(params.xyb),
        subsampling: subsampling as c_int,
    };

    let mut out: *mut u8 = ptr::null_mut();
    let mut out_len: usize = 0;
    let mut err = [0 as c_char; 256];

    // SAFETY: `input` borrows `samples` for the call; `out`/`out_len`/`err` are
    // valid out-params. The shim never retains any pointer past return.
    let rc = unsafe {
        ffi::rawshift_jpegli_encode(&input, &mut out, &mut out_len, err.as_mut_ptr(), err.len())
    };

    if rc != 0 {
        // SAFETY: on failure the shim writes a NUL-terminated message into `err`.
        let msg = unsafe { std::ffi::CStr::from_ptr(err.as_ptr()) }
            .to_string_lossy()
            .into_owned();
        return Err(if msg.is_empty() {
            "jpegli encode failed".to_string()
        } else {
            msg
        });
    }

    // SAFETY: on success `out` is a shim-allocated buffer of `out_len` bytes.
    let data = unsafe { std::slice::from_raw_parts(out, out_len) }.to_vec();
    // SAFETY: free the shim-allocated buffer with the matching allocator.
    unsafe { ffi::rawshift_jpegli_free(out) };
    Ok(data)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 4x4 RGB test pattern at the requested depth (8 or 16 bits), as bytes.
    fn pattern(bits: u32) -> Vec<u8> {
        let px16: [[u16; 3]; 16] = std::array::from_fn(|i| {
            let v = (i as u16) * 4096;
            [v, v.wrapping_add(20000), v.wrapping_add(40000)]
        });
        let mut out = Vec::new();
        for px in px16 {
            for s in px {
                if bits == 16 {
                    out.extend_from_slice(&s.to_ne_bytes());
                } else {
                    out.push((s >> 8) as u8);
                }
            }
        }
        out
    }

    /// Assert `data` is a complete JPEG (SOI … EOI).
    fn assert_jpeg(data: &[u8]) {
        assert!(data.len() > 4, "JPEG output too short");
        assert_eq!(&data[..2], &[0xFF, 0xD8], "missing SOI marker");
        assert_eq!(&data[data.len() - 2..], &[0xFF, 0xD9], "missing EOI marker");
    }

    #[test]
    #[cfg_attr(miri, ignore)] // FFI into jpegli cannot run under Miri.
    fn encodes_valid_jpeg_8bit() {
        let data = encode(&pattern(8), 4, 4, 8, &JpegliEncodeParams::default()).expect("encode");
        assert_jpeg(&data);
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn encodes_valid_jpeg_from_16bit_input() {
        let data = encode(&pattern(16), 4, 4, 16, &JpegliEncodeParams::default())
            .expect("encode 16-bit input");
        assert_jpeg(&data);
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn quality_xyb_and_subsampling_variants_encode() {
        for xyb in [false, true] {
            for subsampling in [
                Subsampling::Yuv420,
                Subsampling::Yuv422,
                Subsampling::Yuv444,
            ] {
                let params = JpegliEncodeParams {
                    quality: Some(80),
                    distance: 1.0,
                    progressive: false,
                    xyb,
                    subsampling,
                };
                let data = encode(&pattern(8), 4, 4, 8, &params)
                    .unwrap_or_else(|e| panic!("encode xyb={xyb} ss={subsampling:?}: {e}"));
                assert_jpeg(&data);
            }
        }
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn distance_is_honoured_over_default() {
        // A larger Butteraugli distance must not error and should not grow the file.
        let low = encode(
            &pattern(8),
            4,
            4,
            8,
            &JpegliEncodeParams {
                distance: 0.5,
                ..JpegliEncodeParams::default()
            },
        )
        .expect("encode d=0.5");
        let high = encode(
            &pattern(8),
            4,
            4,
            8,
            &JpegliEncodeParams {
                distance: 6.0,
                ..JpegliEncodeParams::default()
            },
        )
        .expect("encode d=6.0");
        assert_jpeg(&low);
        assert_jpeg(&high);
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    fn rejects_wrong_buffer_length() {
        let err = encode(&[0u8; 10], 4, 4, 8, &JpegliEncodeParams::default());
        assert!(err.is_err(), "short buffer must be rejected");
    }
}
