[package]
name = "rawshift-image-crw"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Canon CRW decoding for rawshift"

[dependencies]
rawshift-image-core = { workspace = true, features = ["crw-decode"] }

[features]
default = ["decode"]
decode = []
