//! Generate synthetic test fixture files for standard image formats.
//!
//! This binary creates small test images in `test_data/standard/<format>/` and
//! corresponding ground-truth JSON in `test_fixtures/standard/<format>/`.
//!
//! Usage:
//!   cargo run --example generate_test_fixtures
//!
//! The generated fixtures are used by integration tests in
//! `tests/standard_decode_fixtures.rs`.

use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn test_data_dir() -> PathBuf {
    project_root().join("test_data").join("standard")
}

fn test_fixtures_dir() -> PathBuf {
    project_root().join("test_fixtures").join("standard")
}

/// 8x8 RGB pixels with known colors for verification.
/// Row 0: red, green, blue, white, black, cyan, magenta, yellow
/// Rows 1-7: gradient patterns
fn reference_pixels_u8() -> (u32, u32, Vec<u8>) {
    let w = 8u32;
    let h = 8u32;
    let mut pixels = Vec::with_capacity((w * h * 3) as usize);

    // Row 0: primary + secondary colors
    let colors: [(u8, u8, u8); 8] = [
        (255, 0, 0),     // red
        (0, 255, 0),     // green
        (0, 0, 255),     // blue
        (255, 255, 255), // white
        (0, 0, 0),       // black
        (0, 255, 255),   // cyan
        (255, 0, 255),   // magenta
        (255, 255, 0),   // yellow
    ];
    for &(r, g, b) in &colors {
        pixels.extend_from_slice(&[r, g, b]);
    }

    // Rows 1-7: horizontal gradient
    for row in 1..h {
        for col in 0..w {
            let v = ((row * w + col) * 255 / (w * h - 1)) as u8;
            pixels.extend_from_slice(&[v, (255 - v), (v / 2 + 64)]);
        }
    }

    (w, h, pixels)
}

fn write_expected_json(dir: &Path, name: &str, width: u32, height: u32, format: &str) {
    let json = format!(
        r#"{{
  "format": "{}",
  "file_name": "{}",
  "width": {},
  "height": {},
  "channels": 3,
  "bit_depth_output": 16,
  "notes": "Synthetic {} fixture generated by generate_test_fixtures"
}}"#,
        format, name, width, height, format
    );
    fs::write(dir.join("expected.json"), json).expect("write expected.json");
}

fn generate_jpeg(data_dir: &Path, fixture_dir: &Path) {
    let dir = data_dir.join("jpeg");
    let fdir = fixture_dir.join("jpeg");
    fs::create_dir_all(&dir).unwrap();
    fs::create_dir_all(&fdir).unwrap();

    let (w, h, pixels) = reference_pixels_u8();
    let mut encoded = Vec::new();
    let encoder = jpeg_encoder::Encoder::new(&mut encoded, 95);
    encoder
        .encode(&pixels, w as u16, h as u16, jpeg_encoder::ColorType::Rgb)
        .expect("JPEG encode");

    let name = "test_8x8.jpg";
    fs::write(dir.join(name), &encoded).expect("write JPEG");
    write_expected_json(&fdir, name, w, h, "JPEG");
    println!("  Generated {}", name);
}

fn generate_png(data_dir: &Path, fixture_dir: &Path) {
    use zune_core::colorspace::ColorSpace;
    use zune_core::options::EncoderOptions;

    let dir = data_dir.join("png");
    let fdir = fixture_dir.join("png");
    fs::create_dir_all(&dir).unwrap();
    fs::create_dir_all(&fdir).unwrap();

    let (w, h, pixels) = reference_pixels_u8();
    let opts = EncoderOptions::default()
        .set_width(w as usize)
        .set_height(h as usize)
        .set_colorspace(ColorSpace::RGB);
    let mut encoded = Vec::new();
    let mut encoder = zune_png::PngEncoder::new(&pixels, opts);
    encoder.encode(&mut encoded).expect("PNG encode");

    let name = "test_8x8.png";
    fs::write(dir.join(name), &encoded).expect("write PNG");
    write_expected_json(&fdir, name, w, h, "PNG");
    println!("  Generated {}", name);
}

fn generate_gif(data_dir: &Path, fixture_dir: &Path) {
    use gif::{Encoder, Frame, Repeat};
    use std::borrow::Cow;

    let dir = data_dir.join("gif");
    let fdir = fixture_dir.join("gif");
    fs::create_dir_all(&dir).unwrap();
    fs::create_dir_all(&fdir).unwrap();

    // 4x4 GIF with 4-color palette
    let palette: &[u8] = &[
        255, 0, 0, // 0: red
        0, 255, 0, // 1: green
        0, 0, 255, // 2: blue
        255, 255, 255, // 3: white
        0, 0, 0, // padding
        0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];

    let mut out: Vec<u8> = Vec::new();
    let mut encoder = Encoder::new(&mut out, 4, 4, palette).expect("gif encoder");
    encoder.set_repeat(Repeat::Finite(0)).unwrap();

    let mut frame = Frame::default();
    frame.width = 4;
    frame.height = 4;
    // 4x4 grid: alternating pattern
    frame.buffer = Cow::Owned(vec![0, 1, 2, 3, 1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2]);
    encoder.write_frame(&frame).unwrap();
    drop(encoder);

    let name = "test_4x4.gif";
    fs::write(dir.join(name), &out).expect("write GIF");
    write_expected_json(&fdir, name, 4, 4, "GIF");
    println!("  Generated {}", name);
}

fn generate_tiff(data_dir: &Path, fixture_dir: &Path) {
    use tiff::encoder::{TiffEncoder, colortype::RGB8};

    let dir = data_dir.join("tiff");
    let fdir = fixture_dir.join("tiff");
    fs::create_dir_all(&dir).unwrap();
    fs::create_dir_all(&fdir).unwrap();

    let (w, h, pixels) = reference_pixels_u8();
    let mut cursor = Cursor::new(Vec::new());
    {
        let mut enc = TiffEncoder::new(&mut cursor).unwrap();
        enc.write_image::<RGB8>(w, h, &pixels).unwrap();
    }

    let name = "test_8x8.tiff";
    fs::write(dir.join(name), cursor.into_inner()).expect("write TIFF");
    write_expected_json(&fdir, name, w, h, "TIFF");
    println!("  Generated {}", name);
}

fn generate_webp(data_dir: &Path, fixture_dir: &Path) {
    use image_webp::WebPEncoder;

    let dir = data_dir.join("webp");
    let fdir = fixture_dir.join("webp");
    fs::create_dir_all(&dir).unwrap();
    fs::create_dir_all(&fdir).unwrap();

    let (w, h, pixels) = reference_pixels_u8();
    let mut encoded = Vec::new();
    let encoder = WebPEncoder::new(&mut encoded);
    encoder
        .encode(&pixels, w, h, image_webp::ColorType::Rgb8)
        .expect("WebP encode");

    let name = "test_8x8.webp";
    fs::write(dir.join(name), &encoded).expect("write WebP");
    write_expected_json(&fdir, name, w, h, "WebP");
    println!("  Generated {}", name);
}

fn generate_svg(data_dir: &Path, fixture_dir: &Path) {
    let dir = data_dir.join("svg");
    let fdir = fixture_dir.join("svg");
    fs::create_dir_all(&dir).unwrap();
    fs::create_dir_all(&fdir).unwrap();

    let svg = r#"<svg xmlns="http://www.w3.org/2000/svg" width="8" height="8">
  <rect x="0" y="0" width="4" height="4" fill="red"/>
  <rect x="4" y="0" width="4" height="4" fill="green"/>
  <rect x="0" y="4" width="4" height="4" fill="blue"/>
  <rect x="4" y="4" width="4" height="4" fill="white"/>
</svg>"#;

    let name = "test_8x8.svg";
    fs::write(dir.join(name), svg).expect("write SVG");
    write_expected_json(&fdir, name, 8, 8, "SVG");
    println!("  Generated {}", name);
}

fn main() {
    let data_dir = test_data_dir();
    let fixture_dir = test_fixtures_dir();

    println!("Generating standard format test fixtures...");
    println!("  Data dir:    {}", data_dir.display());
    println!("  Fixture dir: {}", fixture_dir.display());
    println!();

    generate_jpeg(&data_dir, &fixture_dir);
    generate_png(&data_dir, &fixture_dir);
    generate_gif(&data_dir, &fixture_dir);
    generate_tiff(&data_dir, &fixture_dir);
    generate_webp(&data_dir, &fixture_dir);
    generate_svg(&data_dir, &fixture_dir);

    println!();
    println!("Done. Run integration tests with:");
    println!("  cargo test --test standard_decode_fixtures");
}
