[package]
name = "rawshift-image-cr3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Canon CR3 decoding for rawshift"

[dependencies]
rawshift-image-core = { workspace = true, features = ["cr3-decode"] }
rawshift-image-ifd = { workspace = true, optional = true }
gamut-ifd = { workspace = true, optional = true, features = ["bigtiff"] }
tracing = { workspace = true, optional = true }

[features]
default = ["decode"]
decode = ["dep:rawshift-image-ifd", "dep:gamut-ifd", "dep:tracing"]
