[package]
name = "rawshift-image-tiff"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "TIFF decoding for rawshift"

[dependencies]
rawshift-image-core = { workspace = true }
tiff = { version = "0.11", optional = true }
serde = { workspace = true, optional = true }

[features]
default = ["decode"]
decode = ["dep:tiff"]
serde = ["dep:serde", "rawshift-image-core/serde"]
